config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  devise_for :users,
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :badges, only: %i[index]

  get '/user_badges', to: 'badges#user_badges'

  # GET /test_passages/101/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index

    resources :badges, except: :index
  end

  resources :feedbacks, only: %i[new create]
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges
  has_many :users, through: :user_badges
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :set_badge, only: %i[edit show update destroy]

  def index
    @badges = Badge.all
  end

  def show; end

  def new
    @badge = Badge.new
  end

  def edit; end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badge_path(@badge), notice: t('.success')
    else
      render :new
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badge_path(@badge), notice: t('.update')
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def set_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:name, :file, :rule, :rule_value)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :authenticate_user!

  def index
    @badges = Badge.all
  end

  def user_badges
    @badges = current_user.badges.all
  end
end

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true do |form| %>
  <%= render 'shared/errors', resource: @badge %>

  <p>
    Choose badge number:
    <%= form.select :file, options_for_select([
                                              [1, '1.png'],
                                              [2, '2.png'],
                                              [3, '3.png'],
                                              [4, '4.png'],
                                              [5, '5.png']
                                              ]) %>

  </p>

  <p>
    <%= form.label :name %>:
    <%= form.text_field :name, id: :badge_name %>
  </p>

  <p>
    <%= form.label :rule %>:
    <%= form.select :rule, options_for_select([
                                              ['level', 'level'],
                                              ['category', 'category'],
                                              ['attempt', 'attempt']
                                              ]) %>
  </p>

  <p>
    <%= form.label :rule_value %>:
    <%= form.text_field :rule_value, id: :badge_rule_value %>
  </p>



  <p><%= form.submit class: 'btn btn-primary' %></p>
<% end %>

app/views/admin/badges/edit.html.erb
<h1><%= t('.header') %></h1>
<p>
  Current bage: <%= image_tag(@badge.file, size: "48") %>
</p>

<p>Choose new badge:</p>

<p>
  1.<%= image_tag('1.png', size: "48") %>
  2.<%= image_tag('2.png', size: "48") %>
  3.<%= image_tag('3.png', size: "48") %>
  4.<%= image_tag('4.png', size: "48") %>
  5.<%= image_tag('5.png', size: "48") %>
</p>

<%= render 'form' %>
<%= link_to t('.back'), admin_badges_path %>

app/views/admin/badges/index.html.erb
<h1><%= t('.header') %></h1>

<p>
  <%= link_to t('.new_badge'), new_admin_badge_path %>
</p>

<table class="table">
  <tr>
    <th>Badge</th>
    <th> <%= t('.name') %></th>
    <th><%= t('.rule') %></th>
    <th colspan="3" ><%= t('.action') %>:</th>
  </tr>

  <%= render @badges %>
</table>

app/views/admin/badges/new.html.erb
<h1><%= t('.header') %></h1>

<p>Choose badge:</p>


<ol>
  <li><%= image_tag('1.png', size: "48") %></li>
  <li><%= image_tag('2.png', size: "48") %></li>
  <li><%= image_tag('3.png', size: "48") %></li>
  <li><%= image_tag('4.png', size: "48") %></li>
  <li><%= image_tag('5.png', size: "48") %></li>
</ol>

<%= render 'form' %>
<%= link_to t('.back'), admin_badges_path %>

app/views/admin/badges/show.html.erb
<p>
  <strong><%= t('.name') %>:</strong>
  <%= @badge.name %>
</p>

<p>
  <%= image_tag(@badge.file, size: "48") %>
</p>

<p>
  <strong><%= t('.rule') %>:</strong>
  <%= @badge.rule %>
</p>

<p>
  <strong><%= t('.rule') %>:</strong>
  <%= @badge.rule_value %>
</p>

<p>
  <%= link_to t('.edit'), edit_admin_badge_path(@badge) %>
  <%= link_to t('.back'), badges_path %>
</p>