config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  devise_for :users,
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :badges, only: %i[index]

  get '/user_badges', to: 'badges#user_badges'

  # GET /test_passages/101/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index

    resources :badges, except: :index
  end

  resources :feedbacks, only: %i[new create]
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges
  has_many :users, through: :user_badges
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :set_badge, only: %i[edit show update destroy]

  def index
    @badges = Badge.all
  end

  def show; end

  def new
    @badge = Badge.new
  end

  def edit; end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badge_path(@badge), notice: t('.success')
    else
      render :new
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badge_path(@badge), notice: t('.update')
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def set_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:name, :file, :rule, :rule_value)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :authenticate_user!

  def index
    @badges = Badge.all
  end

  def user_badges
    @badges = current_user.badges.all
  end
end

app/views/badges/_badge.html.erb
<tr>
  <td class="align-middle"><%= image_tag(badge.file, size: "48") %></td>
  <td class="align-middle"><%= badge.name %></td>
  <td class="align-middle"><%= badge.rule %></td>
  <td class="align-middle"><%= badge.rule_value %></td>
  <% if current_user.admin? %>
    <td><%= link_to t('.show'), admin_badge_path(badge) %></td>
    <td><%= link_to t('.edit'), edit_admin_badge_path(badge) %></td>
    <td><%= link_to t('.delete'),
                admin_badge_path(badge),
                method: :delete,
                data:   { confirm: t('.sure') } %>
    </td>
  <% end %>
</tr>

app/views/badges/index.html.erb
<h1><%= t('.header') %></h1>

<% if current_user.admin? %>
  <%= link_to 'Create badge', new_admin_badge_path  %>
<% end %>

<table class="table">
  <tr>
    <th>Badge</th>
    <th> <%= t('.name') %></th>
    <th><%= t('.rule') %></th>
    <th><%= t('.rule_value') %></th>
    <% if current_user.admin? %>
      <th colspan="3"><%= t('.action') %>:</th>
    <% end %>
  </tr>

  <%= render @badges %>
</table>

<p>
  <%= link_to 'tests', tests_path %> |
  <%= link_to 'earned badges', user_badges_path  %>
</p>

app/views/badges/user_badges.html.erb
<h1><%= t('.header') %></h1>

<p>Earned badges</p>

<table class="table">
  <tr>
    <th>Badge</th>
    <th> <%= t('.name') %></th>
    <th><%= t('.rule') %></th>
    <th><%= t('.rule_value') %></th>

  <%= render @badges %>
</tr>
</table>