config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  devise_for :users,
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :badges, only: %i[index]

  get '/user_badges', to: 'badges#user_badges'

  # GET /test_passages/101/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index

    resources :badges, except: :index
  end

  resources :feedbacks, only: %i[new create]
end

app/models/question.rb
class Question < ApplicationRecord

  belongs_to :test
  has_many :answers

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  attr_reader :number

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true
  before_validation :before_validation_set_question, on: %i[create update]

  SUCCESS_RATE = 85

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)

    save!
  end

  def completed?
    current_question.nil?
  end

  def correct?
    correct_questions == test.questions.count
  end

  def rate
    (correct_questions.to_f / test.questions.count * 100).to_i
  end

  def test_passed?
    rate >= SUCCESS_RATE
  end

  def question_number
    test.questions.index(current_question) + 1
  end

  def time_over?
    (Time.now.to_i - created_at.to_i) >= test.timer
  end

  private

  def before_validation_set_question
    self.current_question = if current_question.nil?
                              first_question
                            else
                              next_question
                            end
  end

  def correct_answer?(answer_ids)
    correct_answers_count = correct_answers.count

    (correct_answers_count == correct_answers.where(id: answer_ids).count) &&
      correct_answers_count == answer_ids.count
  end

  def correct_answers
    current_question.answers.correct
  end

  def first_question
    test.questions.order(:id).first
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show result update gist]

  def show; end

  def result
    user_badges_count = current_user.badges.count

    AwardWithBadges.new(@test_passage).call if @test_passage.correct?

    flash.now[:notice] = 'You have earned new badge!' if current_user.badges.count > user_badges_count
  end

  def update
    if @test_passage.time_over?
      flash[:alert] = 'Time is over, test was interrupted!'
      redirect_to result_test_passage_path(@test_passage)
      return
    end

    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      # TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  def gist
    question = @test_passage.current_question
    service = GistQuestionService.new(question)
    result = service.call

    flash_options =
      if service.success?
        current_user.gists.create(question: question, url: result.html_url)
        gist_link = view_context.link_to 'gist', result.html_url, target: :blank

        { notice: t('.success', gist_link: gist_link) }
      else
        { alert: t('.failure') }
      end

    redirect_to @test_passage, flash_options
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def percents(test_passage)
    "#{test_passage.rate}%"
  end
end

app/views/test_passages/result.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-4">

    <h1><%= t('.header', title: @test_passage.test.title) %></h1>

    <h6><%= t('.indicator') %>:</h6>

    <div class="progress">
      <%= content_tag :div,
                      '40%',
                      class: 'progress-bar',
                      role: 'progressbar',
                      aria_valuenow: '40',
                      aria_valuemin: '0',
                      aria_valuemax: '100',
                      style: 'width:40%'
                       %>

    </div>

    <p>
      <% if @test_passage.test_passed? %>
        <span class="passed"><%= percents(@test_passage) %></span><br>
        Тест пройден.
      <% else %>
        <span class="failed"><%= percents(@test_passage) %></span><br>
        Тест не пройден.
      <% end %>
    </p>

    <p><%= link_to 'All tests', tests_path %></p>
    <p><%= link_to t('.feedback'), new_feedback_path %></p>
  </div>
</div>

app/views/test_passages/show.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-4">

    <h1><%= t('.header', title: @test_passage.test.title) %></h1>

    <h6><%= t('.indicator') %>:</h6>

    <div class="progress">
      <%= content_tag :div,
                      '0%',
                      class: 'progress-bar',
                      role: 'progressbar',
                      aria_valuenow: '0',
                      aria_valuemin: '0',
                      aria_valuemax: '100',
                      data: { questions_count: @test_passage.test.questions_count,
                              question_number: @test_passage.question_number }
                       %>

    </div></br>

    <p>Test time left: <%= content_tag :span,
                                       @test_passage.test.timer,
                                       id: 'timer',
                                       data: { result_link: result_test_passage_url(@test_passage),
                                               start_time: @test_passage.created_at.to_i,
                                               time_amount: @test_passage.test.timer }
                        %>sec.</p>
    <!-- <progress id="timer" value="0" max="100"></progress> -->

    <p>
      <b><%= @test_passage.current_question.body %></b>
    </p>

    <p>
      Вопрос <%= @test_passage.question_number %> из <%= @test_passage.test.questions_count %>
    </p>

    <%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
      <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
        <p>
          <%= b.check_box id: "answer_ids_#{b.object.id}" %>
          <%= b.label %>
        </p>
      <% end %>


      <p><%= link_to 'Gist Question', gist_test_passage_path(@test_passage), method: :post %></p>
      <p><%= form.submit 'Next' %></p>
    <% end %>
  </div>
</div>