config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  devise_for :users,
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :badges, only: %i[index]

  get '/user_badges', to: 'badges#user_badges'

  # GET /test_passages/101/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index

    resources :badges, except: :index
  end

  resources :feedbacks, only: %i[new create]
end

app/models/question.rb
class Question < ApplicationRecord

  belongs_to :test
  has_many :answers

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :find_test, only: %i[create new]
  before_action :find_question, except: %i[new create]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_resource_not_found

  def show; end

  def new
    @question = @test.questions.new
  end

  def edit; end

  def create
    @question = @test.questions.create(question_params)

    if @question.persisted?
      redirect_to admin_question_path(@question)
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to admin_question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy

    redirect_to admin_test_path(@question.test)
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Create New #{question.test.title} Question"
    else
      "Edit #{question.test.title} Question"
    end
  end
end

app/views/admin/questions/_form.html.erb
<%= form_with model: [:admin, @test, @question], local: true do |form| %>
  <%= render 'shared/errors', resource: @question %>

  <p>
    <%= form.label :body %><br>
    <%= form.text_field :body, id: :question_body %>
  </p>

  <p><%= form.submit %></p>
<% end %>

app/views/admin/questions/_question.html.erb
<tr>
  <td><%= question.body %></td>
  <td><%= link_to t('.show'), admin_question_path(question) %></td>
  <td>
  <%= link_to t('.edit'), edit_admin_question_path(question) %>
    <%= link_to t('.delete'),
                admin_question_path(question),
                method: :delete,
                data:   { confirm: t('.sure') } %>
  </td>
</tr>

app/views/admin/questions/edit.html.erb
<h1><%= question_header(@question) %></h1>

<%= render 'form' %>

<%= link_to 'Back', admin_test_path(@question.test) %>

app/views/admin/questions/new.html.erb
<h1><%= question_header(@question) %></h1>

<%= render 'form' %>

<%= link_to 'Back', admin_test_path(@test) %>

app/views/admin/questions/show.html.erb
<h1><%= @question.test.title %> Question</h1>

<p>
  <%= @question.body %>
</p>

<h2>Answers</h2>

<%= link_to 'New answer', new_admin_question_answer_path(@question) %>

<ol>
  <%= render @question.answers %>
</ol>

<%= link_to 'Back', admin_test_path(@question.test) %>
<%= link_to 'Edit', edit_admin_question_path(@question) %>
<%= link_to 'Delete',
                admin_question_path(@question),
                method: :delete,
                data:   { confirm: 'Are you sure?' } %>